console.log("%cJOIN US!", "font-size: 40px; font-weight: bold; color: blue; text-shadow: 2px 2px yellow;");
console.log("%cWe are looking for talented individuals to join our team.", "font-size: 20px; font-weight: bold;");
console.log("%cHere's what we offer:", "font-size: 20px; font-weight: bold;");
console.log("%c- Positive and supportive work culture", "font-size: 16px;");
console.log("%c- Flexible work hours", "font-size: 16px;");
console.log("%c- Opportunities for growth and advancement", "font-size: 16px;");
console.log("%c- The chance to make a real impact at a growing startup", "font-size: 16px;");
console.log("%c- Collaborative and inclusive work environment", "font-size: 16px;");
console.log("%cInterested in joining us?", "font-size: 16px; font-style: italic;");
console.log('https://go.grabasalad.com/IAmCurious');
